# Generated by Django 5.0.2 on 2024-03-17 11:58

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models

import apps.chat.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(max_length=10000, verbose_name='Описание')),
                ('logo', models.FileField(upload_to='chat_topics/logos/', verbose_name='Логотип')),
                ('permission', models.CharField(max_length=255, verbose_name='Права доступа к теме')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'db_table': 'chat_topics',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В процессе'), ('spam', 'Спам'), ('closed', 'Закрыт')], default='new', max_length=25, verbose_name='Статус')),
                ('chat_type', models.CharField(choices=[('topic', 'Тема'), ('order', 'Заказ')], max_length=25, verbose_name='Тип чата')),
                ('curator_note', models.TextField(max_length=10000, null=True, verbose_name='Заметка куратора')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_chats', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('curator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_chats', to=settings.AUTH_USER_MODEL, verbose_name='Куратор')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.chattopic', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('text', models.TextField(max_length=10000, null=True, verbose_name='Текст')),
                ('message_type', models.CharField(choices=[('emoji', 'Эмодзи'), ('text', 'Текст'), ('file', 'Файл')], max_length=25, verbose_name='Тип сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chat', verbose_name='Чат')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чатов',
                'db_table': 'chat_messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ChatMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('file', models.FileField(upload_to=apps.chat.models.ChatMessageFile._get_file_path, verbose_name='Файл')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='chat.chatmessage', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Файл сообщения',
                'verbose_name_plural': 'Файлы сообщений',
                'db_table': 'chat_message_files',
            },
        ),
    ]
