# Generated by Django 5.0.2 on 2024-04-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='status',
            field=models.CharField(choices=[('open', 'Открытый'), ('in_progress', 'В процессе'), ('closed', 'Закрыт'), ('delayed', 'Отложен')], default='open', max_length=25, verbose_name='Статус'),
        ),
    ]
