# Generated by Django 5.0.2 on 2024-04-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='closed_at',
            field=models.DateTimeField(null=True, verbose_name='Дата закрытия'),
        ),
    ]
